### PR TITLE
Ensure checkNodeModules always returns a promise

### LINKED ISSUE #134: wt create --bundle --ignore-package-json throws error when package.json contains no dependencies
If you try to create a bundled webtask that has a package.json with no dependencies and you use the `--ignore-package-json` flag, the command fails.

I have created an example [here](https://github.com/toboid/wt-cli/tree/webtask-no-deps/sample-webtasks/bundled-webtask-no-deps). When created with command `wt create --bundle --ignore-package-json .` the cli throws the following error:

```
Uncaught error:  Cannot read property 'then' of undefined
```

I was using `--ignore-package-json` in order to work around #133. The combination of these 2 issues means that it's not currently possible to create a bundled webtask that has no module dependencies

### PR DESCRIPTION
**Pull request by toboid**
Add a default return value of a promise for an empty array to `checkNodeModules`. The empty array is to be consistent with the return values from the other 2 returns in this function, which both return an array of modules.

Fixes #134

### CODE REVIEW

File: lib/webtaskCreator.js [hunk 1]
```diff
@@ -72,6 +72,8 @@ function createWebtaskCreator(args, options) {
                         });
                 });
         }
+
+        return Promise.resolve([]);
```
Comment (ggoodman) [inline lib/webtaskCreator.js]: Wow, big oversight on my part! Nice catch.
